package controllers

import scala.collection.mutable.ListBuffer

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

class Problem2 {

  def fiboList (a : Int, b : Int) = {

    var x = a
    var y = b
    var z = a + b
    val list = ListBuffer[Int]()

    while (y <= 4000000) {

      z = x + y
      list += x
      x = y
      y = z
    }

    list.toList.filter(i => i % 2 == 0).sum

  }

  fiboList(1, 2)
}
